import { Processo } from '@/lib/mock-data'

export const ACOMPANHAMENTO_MOCKS: Processo[] = [
  {
    id: 'proc-m001',
    numero: '0234567-88.2025.8.26.0100',
    produto: 'Conta Corrente',
    vara: '3ª Vara Cível',
    comarca: 'São Paulo',
    tribunal: 'TJSP',
    tipoSubsidio: 'Dano Moral',
    tipoAcao: 'Ação de Indenização por Dano Moral',
    faseProcessual: 'Conhecimento',
    valorCausa: 25000,
    dataEntrada: '2025-11-10',
    dataDistribuicao: '2025-11-12',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'Pedro Lima',
    nomeAutor: 'Carlos Eduardo Souza',
    cpfAutor: '123.456.789-00',
    advogadoAutor: 'Dr. Rafael Alves',
    oabAdvogadoAutor: 'OAB/SP 245.001',
    advogadoReu: 'Dra. Mariana Costa',
    protocoloServiceNow: 'SN-2026-18472',
    statusServiceNow: 'aguardando',
    tempoDesdeEnvio: '45min',
    timestampEnvio: '2026-04-23T08:15:00.000Z',
    analise: {
      tipoRisco: 'Médio',
      probabilidade: 'Possível',
      valorRecomendado: '8000',
      estrategia: 'Propor acordo',
      fundamento: 'Histórico de acordos favoráveis em casos similares de dano moral.',
    },
  },
  {
    id: 'proc-m002',
    numero: '0189234-45.2025.8.26.0050',
    produto: 'Cartão de Crédito',
    vara: '2ª Vara Cível',
    comarca: 'Campinas',
    tribunal: 'TJSP',
    tipoSubsidio: 'Cobrança Indevida',
    tipoAcao: 'Ação de Repetição de Indébito',
    faseProcessual: 'Conhecimento',
    valorCausa: 12500,
    dataEntrada: '2025-12-01',
    dataDistribuicao: '2025-12-05',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'Ana Costa',
    nomeAutor: 'Fernanda Lima Ribeiro',
    cpfAutor: '234.567.890-11',
    advogadoAutor: 'Dra. Beatriz Fonseca',
    oabAdvogadoAutor: 'OAB/SP 189.022',
    advogadoReu: 'Dr. Lucas Andrade',
    protocoloServiceNow: 'SN-2026-21033',
    statusServiceNow: 'em_geracao',
    tempoDesdeEnvio: '2h',
    timestampEnvio: '2026-04-23T06:45:00.000Z',
    analise: {
      tipoRisco: 'Baixo',
      probabilidade: 'Provável',
      valorRecomendado: '12500',
      estrategia: 'Pagar integralmente',
      fundamento: 'Cobrança comprovadamente indevida com documentação completa.',
    },
  },
  {
    id: 'proc-m003',
    numero: '0301122-77.2025.8.26.0300',
    produto: 'Empréstimo Pessoal',
    vara: '5ª Vara Cível',
    comarca: 'Santos',
    tribunal: 'TJSP',
    tipoSubsidio: 'Revisional',
    tipoAcao: 'Ação Revisional de Contrato Bancário',
    faseProcessual: 'Recursal',
    valorCausa: 47000,
    dataEntrada: '2025-09-15',
    dataDistribuicao: '2025-09-20',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'Carla Mendes',
    nomeAutor: 'Roberto Nascimento',
    cpfAutor: '345.678.901-22',
    advogadoAutor: 'Dr. Henrique Moura',
    oabAdvogadoAutor: 'OAB/SP 311.099',
    advogadoReu: 'Dra. Sofia Brandão',
    protocoloServiceNow: 'SN-2026-19874',
    statusServiceNow: 'em_geracao',
    tempoDesdeEnvio: '4h',
    timestampEnvio: '2026-04-23T04:30:00.000Z',
    analise: {
      tipoRisco: 'Alto',
      probabilidade: 'Provável',
      valorRecomendado: '22000',
      estrategia: 'Propor acordo',
      fundamento: 'Jurisprudência recente favorável ao autor em casos de revisão de taxas.',
    },
  },
  {
    id: 'proc-m004',
    numero: '0412890-33.2025.8.26.0070',
    produto: 'Financiamento Imobiliário',
    vara: '1ª Vara Cível',
    comarca: 'Ribeirão Preto',
    tribunal: 'TJSP',
    tipoSubsidio: 'Revisional',
    tipoAcao: 'Ação Revisional de Mútuo Hipotecário',
    faseProcessual: 'Execução',
    valorCausa: 185000,
    dataEntrada: '2025-07-10',
    dataDistribuicao: '2025-07-14',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'João Ferreira',
    nomeAutor: 'Marcia Helena Teixeira',
    cpfAutor: '456.789.012-33',
    advogadoAutor: 'Dr. Paulo Rezende',
    oabAdvogadoAutor: 'OAB/SP 401.055',
    advogadoReu: 'Dr. André Vasconcelos',
    protocoloServiceNow: 'SN-2026-15290',
    statusServiceNow: 'laudo_gerado',
    tempoDesdeEnvio: '1d',
    timestampEnvio: '2026-04-22T08:00:00.000Z',
    analise: {
      tipoRisco: 'Crítico',
      probabilidade: 'Certa',
      valorRecomendado: '95000',
      estrategia: 'Encaminhar ao jurídico externo',
      fundamento: 'Caso de alta complexidade com precedente desfavorável no STJ.',
    },
  },
  {
    id: 'proc-m005',
    numero: '0523411-19.2024.8.26.0150',
    produto: 'Conta Salário',
    vara: '4ª Vara Cível',
    comarca: 'Santo André',
    tribunal: 'TJSP',
    tipoSubsidio: 'Negativação Indevida',
    tipoAcao: 'Ação de Danos Morais por Negativação Indevida',
    faseProcessual: 'Conhecimento',
    valorCausa: 18000,
    dataEntrada: '2024-11-20',
    dataDistribuicao: '2024-11-25',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'Pedro Lima',
    nomeAutor: 'Sílvio Gomes Pereira',
    cpfAutor: '567.890.123-44',
    advogadoAutor: 'Dra. Camila Nunes',
    oabAdvogadoAutor: 'OAB/SP 278.033',
    advogadoReu: 'Dr. Fábio Lemos',
    protocoloServiceNow: 'SN-2026-11847',
    statusServiceNow: 'entregue',
    tempoDesdeEnvio: '2d',
    timestampEnvio: '2026-04-21T10:00:00.000Z',
    analise: {
      tipoRisco: 'Baixo',
      probabilidade: 'Possível',
      valorRecomendado: '5000',
      estrategia: 'Propor acordo',
      fundamento: 'Negativação reconhecidamente indevida. Recomendado acordo para mitigar custos.',
    },
  },
  {
    id: 'proc-m006',
    numero: '0634500-02.2025.8.26.0250',
    produto: 'Seguro de Vida',
    vara: '6ª Vara Cível',
    comarca: 'Osasco',
    tribunal: 'TJSP',
    tipoSubsidio: 'Fraude',
    tipoAcao: 'Ação de Indenização Securitária',
    faseProcessual: 'Conhecimento',
    valorCausa: 68000,
    dataEntrada: '2025-10-05',
    dataDistribuicao: '2025-10-10',
    status: 'Enviado ao ServiceNow',
    analistaResponsavel: 'Carla Mendes',
    nomeAutor: 'Aparecida Santos Rodrigues',
    cpfAutor: '678.901.234-55',
    advogadoAutor: 'Dr. Gustavo Almeida',
    oabAdvogadoAutor: 'OAB/SP 360.077',
    advogadoReu: 'Dra. Renata Coelho',
    protocoloServiceNow: 'SN-2026-22591',
    statusServiceNow: 'pendencia',
    tempoDesdeEnvio: '3h',
    timestampEnvio: '2026-04-23T05:45:00.000Z',
    pendenciaDescricao: 'CPF do autor não localizado na base do ServiceNow. Verificar documento enviado e corrigir antes de reenviar o payload.',
    analise: {
      tipoRisco: 'Alto',
      probabilidade: 'Provável',
      valorRecomendado: '34000',
      estrategia: 'Contestar',
      fundamento: 'Indícios de fraude documental. Recomendada contestação com perícia técnica.',
    },
  },
]
